name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        working-directory: ./welcome_website
        run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /welcome_materials

      - name: Export
        working-directory: ./welcome_website
        run: npm run export
        env:
          NEXT_PUBLIC_BASE_PATH: /welcome_materials

      - name: Prevent underscore
        working-directory: ./welcome_website
        run: touch ./out/.nojekyll

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./welcome_website/out # The folder the action should deploy.
